🐞 `pci_passthroughs` reserve memory
When `pci_passthroughs` are configured,
`memory_reservation_locked_to_max` should also be set, but wasn't,
causing deploys to fail.

With this commit, `memory_reservation_locked_to_max` is now set when
`pci_passthroughs` are configured.

Fixes, during `bosh deploy`:
```
Error: Unknown CPI error 'Unknown' with message 'Invalid memory setting: memory reservation (sched.mem.min) should be equal to memsize(32768). ' in 'create_vm' CPI method
```

**[Bug Fix]** vSphere reserves memory when `pci_passthroughs` are
configured, allowing deployments to succeed.