Update disk uuid to use dig in case of nil/setting not used
If cpi config doesn't contain value for disk.enableUUID the current code breaks with below error.
that is because the config is optional and may not be present. use dig to safely access the value or return nil if it's not present

Fixes:
```
      NoMethodError:
        undefined method `[]' for nil:NilClass

              vcenter['disk']['enableUUID']
```

Signed-off-by: Konstantin Kiess <kkiess@vmware.com>